### **Arrays**

**TASK**

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

Input Format

A single line of input containing space separated numbers.

Output Format

Print the reverse NumPy array with type float.

In [ ]:
import numpy

def arrays(arr):
    arr= numpy.array(arr,float)
    return(arr[::-1])
    
    
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### **Shape and Reshape**

**TASK**

You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

Input Format

A single line of input containing 9 space separated integers.

Output Format

Print the 3X3 NumPy array.

In [ ]:
import numpy
arr=numpy.array(input().split(),int)
print(numpy.reshape(arr,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### **Transpose and Flatten**

**TASK**

You are given a NXM integer array matrix with space separated elements ( N= rows and  M= columns).
Your task is to print the transpose and flatten results.

Input Format

The first line contains the space separated values of N and M.
The next N lines contains the space separated elements of M columns.

In [ ]:
import numpy
n, m = map(int, input().split())
arr= numpy.array([input().split() for _ in range(n)],int)
print(arr.transpose(),arr.flatten(),sep="\n")


3 3
1 2
3 4
5 6
[[1 3 5]
 [2 4 6]]
[1 2 3 4 5 6]


### **Concatenate**

**TASK**

You are given two integer arrays of size NXP and MXP (N &M  are rows, and P is the column). Your task is to concatenate the arrays along axis O.

In [ ]:
import numpy
N,M,P= map(int,input().split())
arr= numpy.array([input().split() for _ in range(N+M)],int)
print(arr)

4 3 2
1 2
2 3
3 4 
4 5
5 6
6 7
7 8
[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]
 [6 7]
 [7 8]]


### **Zeros and Ones**

**TASK**

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

Input Format

A single line containing the space-separated integers.

In [1]:
import numpy
dimensions=list(map(int,input().split()))
print(numpy.zeros(dimensions, dtype = numpy.int))
print(numpy.ones(dimensions, dtype = numpy.int))
  

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


### **Eye and Identity**

**TASK**

Your task is to print an array of size NXM with its main diagonal elements as 1's and 0's everywhere else.

Input Format

A single line containing the space separated values of N and M.
N denotes the rows.
M denotes the columns.

Output Format

Print the desired NXM array.

In [9]:
import numpy
N,M=map(int,input().split())
numpy.set_printoptions(sign=' ')
print( numpy.eye(N,M))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### **Floor, Ceil and Rint**

**TASK**

You are given a 1-D array, A. Your task is to print the floor,ceil  and rint of all the elements of A.

In [24]:
import numpy
arr=numpy.array(input().split(),float)
print(numpy.floor(arr),numpy.ceil(arr),numpy.rint(arr),sep="\n")

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


### **Sum and Prod**

**TASK**

You are given a 2-D array with dimensions NXM.
Your task is to perform the sum tool over axis 0 and then find the product of that result.



In [30]:
N,M= map(int,input().split())
arr=numpy.array([input().split() for _ in range(N)],int)
s=numpy.sum(arr,axis=0)
print(numpy.prod(s))

2 2
1 2
3 4
24


### **Min and Max**

**TASK**

You are given a 2-D array with dimensions MXN.
Your task is to perform the min function over axis 1 and then find the max of that.

In [32]:
N,M= map(int,input().split())
arr=numpy.array([input().split() for _ in range(N)],int)
mi=numpy.min(arr,axis=1)
print(numpy.max(mi))

4 2
2 5
3 7
1 3
4 0
3


### **Mean, Var, and Std**

**TASK**

You are given a 2-D array of size X.
Your task is to find:

The mean along axis 1

The var along axis 0

The std along axis none


In [35]:
N,M= map(int,input().split())
arr=numpy.array([input().split() for _ in range(N)],int)
print(numpy.mean(arr,axis=1),numpy.var(arr,axis=0),round(numpy.std(arr),11),sep="\n")

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


### **Dot and Cross**

**TASK**

You are given two arrays A and B. Both have dimensions of NXN.
Your task is to compute their matrix product.

In [39]:
N=int(input())
arr1= numpy.array([input().split() for _ in range(N)],int)
arr2= numpy.array([input().split() for _ in range(N)],int)
print(numpy.dot(arr1,arr2))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


### **Inner and Outer**

**TASK**

You are given two arrays: A and B.
Your task is to compute their inner and outer product.

In [41]:
import numpy
A=numpy.array(input().split(),int)
B=numpy.array(input().split(),int)
print(numpy.inner(A,B),numpy.outer(A,B),sep="\n")


0 1
2 3
3
[[0 0]
 [2 3]]


### **Polynomials**

**TASK**

You are given the coefficients of a polynomial P.
Your task is to find the value of P at point x.

In [45]:
 import numpy
P = list(map(float,input().split()))
x=input()
print(numpy.polyval(P, float(x)))

1.1 2 3
0
3.0


### **Linear Algebra**

**TASK**

You are given a square matrix A with dimensions NXN. Your task is to find the determinant. Note: Round the answer to 2 places after the decimal.

Input Format

The first line contains the integer N.
The next N lines contains the N space separated elements of array A.

In [50]:
print(round(numpy.linalg.det(numpy.array([input().split() for _ in range(int(input()))],float)),2))

2
1.1 1.1
1.1 1.1
0.0


In [52]:
N=int(input())
arr=numpy.array([input().split() for _ in range(N)],float)
print(round(numpy.linalg.det(arr),2))

2
1.1 1.1
1.1 1.1
0.0
