### ***List Comprehensions***



***Task***

Let's learn about list comprehensions! You are given three integers x,y  and z representing the dimensions of a cuboid along with an integer n . Print a list of all possible coordinates given by(i,j,k)  on a 3D grid where the sum of i+j+k  is not equal to n . Here, . Please use list comprehensions rather than multiple loops, as a learning exercise.

In [ ]:
x,y,z,n= (int(input()) for i in range(4)) # iterating loops for four times to take the inputs
print([[i,j,k] for i  in range(x+1) for j in range(y+1) for k in range(z+1) if sum([i,j,k])!=n]) ## list comprehensioning the given condition

### ***Find the Runner-Up Score!***



***Task***

Given the participants' score sheet for your University Sports Day, you are required to find the runner-up score. You are given n scores. Store them in a list and find the score of the runner-up.

In [ ]:
A=[]
n= int(input())
for i in range(n):
  k=int(input())
  A.append(k)
print(A)
print(sorted((set(A)))[-2])

5
5
4
2
5
4
[5, 4, 2, 5, 4]
4


#### ***Nested Lists***

***TASK***

Given the names and grades for each student in a class of N  students, store them in a nested list and print the name(s) of any student(s) having the second lowest grade.

In [ ]:
record = {}
n = int(input())
for x in range(n):
    name = input()
    score = float(input())
    
    if score in record:
        record[score].append(name)
    else:
        record[score] = [name]
        
all_marks = sorted(list(set(record.keys())))
names_ordered = record[all_marks[1]]
names_ordered.sort()

for name in names_ordered:
    print (name)

5
a
37.21
b
37.21
c37.2
37.2
d
41
e
39
a
b


### ***Finding the percentage***

**Task**

The provided code stub will read in a dictionary containing key/value pairs of name:[marks] for a list of students. Print the average of the marks array for the student name provided, showing 2 places after the decimal.

In [ ]:
  n = int(input())
  student_marks = {}
  for _ in range(n):
    name, *line = input().split()
    scores = list(map(float, line))
    student_marks[name] = scores
  query_name = input()
    
  for key, value in student_marks.items():
    if query_name == key:
      total = 0
      c = 0
      for i in value:
        total += i
        c += 1
      average = total/c
      print("{:.2f}".format(average))
    


3
Krishna 67 68 69
Arjun 70 98 63
Malika 52 56 60
Malika
56.00


### **Array Mathematics**

**TASK**

Basic mathematical functions operate element-wise on arrays. They are available both as operator overloads and as functions in the NumPy module.
Add ( + )
Subtract ( - )
Multiply ( * )
Integer Division ( / )
Mod ( % )
Power ( ** )

In [ ]:
import numpy as np
N,M= (int(input()) for i in range(2))
A, B = (np.array([input().split() for _ in range(n)], dtype=int) for _ in range(2))
print(np.add(A,B), np.subtract(A,B), np.multiply(A,B,), np.floor_divide(A,B), np.mod(A,B), np.power(A,B),sep='\n')

3
3
1
2
3
4
5
6
[[5]
 [7]
 [9]]
[[-3]
 [-3]
 [-3]]
[[ 4]
 [10]
 [18]]
[[0]
 [0]
 [0]]
[[1]
 [2]
 [3]]
[[  1]
 [ 32]
 [729]]


  ### ***LIST***

**TASK**

Consider a list (list = []). You can perform the following commands:

insert i e: Insert integer e at position i .
print: Print the list.
remove e: Delete the first occurrence of integer e .
append e: Insert integer e at the end of the list.
sort: Sort the list.
pop: Pop the last element from the list.
reverse: Reverse the list.

In [9]:
n = int(input())
L = []
for t in range(n):
  arr = input().split(" ")
  if arr[0] == "append":
    L.append(int(arr[1]))
  elif arr[0] == "remove":
    L.remove(int(arr[1]))
  elif arr[0] == "reverse":
    L.reverse()
  elif arr[0] == "pop":
    L.pop()
  elif arr[0] == "insert":
     L.insert(int(arr[1]), int(arr[2]))
  elif arr[0] == "sort":
    L.sort()
  elif arr[0] == "print":
    print (L) 

12
insert 0 5
insert 1 10
insert 0 6
print
[6, 5, 10]
remove 6
append 9
append 1
sort
print
[1, 5, 9, 10]
pop
reverse
print
[9, 5, 1]


### **Tuples**

**TASK**

Given an integer, n, and n space-separated integers as input, create a tuple, t, of those n integers. Then compute and print the result of hash(t) .

In [12]:
 n = int(input())
integer_list = map(int, input().split())
print(hash(tuple(integer_list)))

2
1 2
3713081631934410656


### **Introduction to Sets**

**TASK**

Ms. Gabriel Williams is a botany professor at District College. One day, she asked her student Mickey to compute the average of all the plants with distinct heights in her greenhouse.

In [42]:
n=int(input()) # no.of elements in  the list
arr = [int(i) for i in input().split()] # entering the elements in the list at a once 
total=sum(set(arr))
c=len(set(arr))
aver=total/c
print(aver)

5
1 2 3 4 5 6
3.5


### **Symmetric Difference**

**TASK**

Given 2 sets of integers, M and N, print their symmetric difference in ascending order. The term symmetric difference indicates those values that exist in either M or N but do not exist in both.



In [3]:
M,m=(int(input()),input().split())
N,n=(int(input()),input().split())
x=set(m)
y=set(n)
i=y.difference(x)
j=x.difference(y)
k=i.union(j)
print ('\n'.join(sorted(k, key=int)))

4
2 4 5 9
4
2 4 11 12
5
9
11
12


### **No Idea!**

**TASK**

There is an array of n integers. There are also 2 disjoint sets,A  and B, each containing m integers. You like all the integers in set A and dislike all the integers in set B . Your initial happiness is 0. For each i integer in the array, if , you add  to your happiness. If , you add  to your happiness. Otherwise, your happiness does not change. Output your final happiness at the end.

In [4]:
a=input().split(' ')
l=([int(i) for i in input().split(' ')])
set1=set([int(i) for i in input().split(' ')])
set2=set([int(i) for i in input().split(' ')])
happiness=0
for i in l:
    if i in set1:
        happiness+=1
    if i in set2:
        happiness-=1
print(happiness)


3 2
1 5 3
3 1
5 7
1


### **Set .add()**

**TASK**

Rupal has a huge collection of country stamps. She decided to count the total number of distinct country stamps in her collection. She asked for your help. You pick the stamps one by one from a stack of N country stamps.

Find the total number of distinct country stamps.

In [10]:
n=int(input())
m=[]
for i in range(n):
  j=input()
  m.append(j)
print(len(set(m)))


5
raj
kiran
dvs
raj
kiran
3


### **Set .discard(), .remove() & .pop()**



**TASK**

The first line contains integer n, the number of elements in the set 8.
The second line contains n space separated elements of set 8. All of the elements are non-negative integers, less than or equal to 9.
The third line contains integer N, the number of commands.
The next N lines contains either pop, remove and/or discard commands followed by their associated value.

In [21]:
n = int(input())
r = set(map(int, input().split())) 
commands = int(input())

for i in range(commands):

    c, *args = map(str,input().split())

    getattr(r,c) (*(int(x) for x in args))

print (sum(r))


2
1 2
1
remove 1
2


### **Set .union() Operation**

  ##### **TASK**

  The students of District College have subscriptions to English and French newspapers. Some students have subscribed only to English, some have subscribed to only French and some have subscribed to both newspapers.

You are given two sets of student roll numbers. One set has subscribed to the English newspaper, and the other set is subscribed to the French newspaper. The same student could be in both sets. Your task is to find the total number of students who have subscribed to at least one newspaper.



In [27]:
a= int(input())
s1= set([ x for x in input().split()])
b= int(input())
s2= set([ x for x in input().split()])
print(len(s1.union(s2)))

9
9
1 2 3 4 5 6 7 8 9
10 1 2 3 11 21 55 6 8
13


### **Set .intersection() Operation**

**TASK**

The students of District College have subscriptions to English and French newspapers. Some students have subscribed only to English, some have subscribed only to French, and some have subscribed to both newspapers.

You are given two sets of student roll numbers. One set has subscribed to the English newspaper, one set has subscribed to the French newspaper. Your task is to find the total number of students who have subscribed to both newspapers.

In [28]:
a= int(input())
s1= set([ x for x in input().split()])
b= int(input())
s2= set([ x for x in input().split()])
print(len(s1.intersection(s2)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
5


### **Set .difference() Operation**

**TASK**

Students of District College have a subscription to English and French newspapers. Some students have subscribed to only the English newspaper, some have subscribed to only the French newspaper, and some have subscribed to both newspapers.

You are given two sets of student roll numbers. One set has subscribed to the English newspaper, and one set has subscribed to the French newspaper. Your task is to find the total number of students who have subscribed to only English newspapers.

In [29]:
a= int(input())
s1= set([ x for x in input().split()])
b= int(input())
s2= set([ x for x in input().split()])
print(len(s1.difference(s2)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


### **Set .symmetric_difference() Operation**

**TASK**

Students of District College have subscriptions to English and French newspapers. Some students have subscribed to English only, some have subscribed to French only, and some have subscribed to both newspapers.

You are given two sets of student roll numbers. One set has subscribed to the English newspaper, and one set has subscribed to the French newspaper. Your task is to find the total number of students who have subscribed to either the English or the French newspaper but not both

In [30]:
a= int(input())
s1= set([ x for x in input().split()])
b= int(input())
s2= set([ x for x in input().split()])
print(len(s1.symmetric_difference(s2)))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
8


### **Set Mutations**

**TASK**
You are given a set A and N number of other sets. These  N number of sets have to perform some specific mutation operations on set A .
Your task is to execute those operations and print the sum of elements from set A.



In [43]:
k=input()
s1=set(map(int,input().split()))
n=int(input())
for i in range(0,n):
   
    oper=input().split()[0]
    s2=set(map(int,input().split()))
    if oper=="intersection_update":
        s1.intersection_update(s2)
    if oper=="update":
        s1.update(s2)
    if oper=="difference_update":
        s1.difference_update(s2)
    if oper=="symmetric_difference_update":
        s1.symmetric_difference_update(s2)
print (sum(s1) )

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
38


### **The Captain's Room**

**TASK**

Mr. Anant Asankhya is the manager at the INFINITE hotel. The hotel has an infinite amount of rooms.

One fine day, a finite number of tourists come to stay at the hotel.
The tourists consist of:
→ A Captain.
→ An unknown group of families consisting of K members per group where K ≠1 .

The Captain was given a separate room, and the rest were given one room per group.

Mr. Anant has an unordered list of randomly arranged room entries. The list consists of the room numbers for all of the tourists. The room numbers will appear K times per group except for the Captain's room.

Mr. Anant needs you to help him find the Captain's room number.
The total number of tourists or the total number of groups of families is not known to you.
You only know the value of K and the room number list.

In [45]:
K = int(input())
num = map(int,input().split())

c = {}
for n in num:
    if n in c:
        c[n] += 1
    else:
        c[n] = 1
for n in c:
    if c[n] == 1:
        print (n)
        break

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
8


### **Check Subset**

**TASK**

You are given two sets, A and B .
Your job is to find whether set A is a subset of set B.

If set A is subset of set B , print True.
If set A is not a subset of set B, print False.

In [46]:
for i in range (int(input())):
   _, p = input(), set(input().split())
   _, q = input(), set(input().split())
    print(q.intersection(p) == p)

3
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 1
False
7
1 2 3 5 6 8 9
3
9 8 2
False


### **Check Strict Superset**

**TASK**

You are given a set A and n other sets.
Your job is to find whether set A is a strict superset of each of the N sets.

Print True, if A is a strict superset of each of the N sets. Otherwise, print False.

A strict superset has at least one element that does not exist in its subset.

In [47]:
a = set(input().split())
c , n = 0, int(input())
for i in range (n):
        b = set(input().split())
        if a.issuperset(b) :
                c=c+ 1
print(c== n)

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False
